# Generated by Django 5.1.7 on 2025-03-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('IdClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Fonction', models.CharField(blank=True, max_length=100)),
                ('CodePostal', models.CharField(max_length=10)),
                ('Ville', models.CharField(max_length=100)),
                ('Adresse', models.TextField()),
                ('Telephone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('RaisonSociale', models.CharField(blank=True, max_length=200)),
                ('SIRET', models.CharField(blank=True, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('idCommercial', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('IdProduit', models.AutoField(primary_key=True, serialize=False)),
                ('NomProduit', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('TypeProduit', models.CharField(choices=[('MATERIEL', 'Matériel'), ('LOGICIEL', 'Logiciel'), ('SERVICE', 'Service'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de produit')),
                ('PrixHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT')),
                ('PrixTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix TTC')),
                ('QuantiteStock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('IdMouvement', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de mouvement')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('IdCommande', models.AutoField(primary_key=True, serialize=False)),
                ('DateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('Statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la commande')),
                ('MontantTotalHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total HT')),
                ('MontantTotalTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-DateCommande'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('IdDevis', models.AutoField(primary_key=True, serialize=False)),
                ('MontantTotalHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total HT')),
                ('MontantTotalTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.client', verbose_name='Client')),
                ('idCommercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to='api.commercial', verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='Ristourne',
            fields=[
                ('idRistourne', models.AutoField(primary_key=True, serialize=False)),
                ('DateRistourne', models.DateField(verbose_name='Date de la ristourne')),
                ('Montant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la ristourne')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristournes', to='api.client', verbose_name='Client')),
                ('IdCommercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ristournes_accordees', to='api.commercial', verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Ristourne',
                'verbose_name_plural': 'Ristournes',
                'ordering': ['-DateRistourne'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
