# Generated by Django 5.2.2 on 2025-06-10 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('IdLivreur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('CodePostal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('Ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('DateEmbauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('Statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('MALADE', 'Arrêt maladie')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('IdProduit', models.AutoField(primary_key=True, serialize=False)),
                ('NomProduit', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('TypeProduit', models.CharField(choices=[('MATERIEL', 'Matériel'), ('LOGICIEL', 'Logiciel'), ('SERVICE', 'Service'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de produit')),
                ('PrixHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT')),
                ('PrixTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix TTC')),
                ('QuantiteStock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('IdMouvement', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de mouvement')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('IdVehicule', models.AutoField(primary_key=True, serialize=False)),
                ('TypeVehicule', models.CharField(choices=[('CAMION', 'Camion'), ('UTILITAIRE', 'Utilitaire'), ('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('AUTRE', 'Autre')], default='CAMION', max_length=20, verbose_name='Type de véhicule')),
                ('Statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_UTILISATION', 'En utilisation'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20, verbose_name='Statut du véhicule')),
                ('LastDateMaintenance', models.DateField(blank=True, null=True, verbose_name='Dernière date de maintenance')),
                ('Immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('role', models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Collaborateur'), (4, 'Fournisseur')], verbose_name='Rôle')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison Sociale')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_miseajour', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('IdCommande', models.AutoField(primary_key=True, serialize=False)),
                ('DateCommande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('Statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la commande')),
                ('MontantTotalHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total HT')),
                ('MontantTotalTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('EstPayee', models.BooleanField(default=False, verbose_name='Est payée')),
                ('DatePaiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-DateCommande'],
            },
        ),
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IdCommande', models.IntegerField(verbose_name='ID de la commande')),
                ('IdProduit', models.IntegerField(verbose_name='ID du produit')),
                ('Quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
            ],
            options={
                'verbose_name': 'Détail de commande',
                'verbose_name_plural': 'Détails de commandes',
                'unique_together': {('IdCommande', 'IdProduit')},
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('IdDevis', models.AutoField(primary_key=True, serialize=False)),
                ('MontantTotalHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total HT')),
                ('MontantTotalTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('idCommercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('IdEntrepot', models.AutoField(primary_key=True, serialize=False)),
                ('Localisation', models.CharField(max_length=255, verbose_name="Localisation de l'entrepôt")),
                ('CapaciteStock', models.PositiveIntegerField(default=0, verbose_name='Capacité de stockage')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='api.product', verbose_name='Produit associé')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='Ristourne',
            fields=[
                ('idRistourne', models.AutoField(primary_key=True, serialize=False)),
                ('DateRistourne', models.DateField(verbose_name='Date de la ristourne')),
                ('MontantRistourne', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la ristourne')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('IdCommercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ristournes_accordees', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('IdDevis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristournes', to='api.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ristourne',
                'verbose_name_plural': 'Ristournes',
                'ordering': ['-DateRistourne'],
            },
        ),
        migrations.CreateModel(
            name='StockMouvement',
            fields=[
                ('IdMouvement', models.AutoField(primary_key=True, serialize=False)),
                ('DateMouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('Quantite', models.IntegerField(verbose_name='Quantité')),
                ('TypeMouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR', 'Retour'), ('AJUSTEMENT', 'Ajustement'), ('INVENTAIRE', 'Inventaire')], default='ENTREE', max_length=20, verbose_name='Type de mouvement')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('IdCommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.commande', verbose_name='Commande associée')),
                ('IdEntrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.entrepot', verbose_name='Entrepôt')),
                ('IdFournisseur', models.ForeignKey(blank=True, limit_choices_to={'role': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_fournisseur', to=settings.AUTH_USER_MODEL, verbose_name='Fournisseur')),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-DateMouvement'],
            },
        ),
        migrations.AddField(
            model_name='entrepot',
            name='IdMouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_associes', to='api.stockmouvement', verbose_name='Dernier mouvement associé'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('IdTransport', models.AutoField(primary_key=True, serialize=False)),
                ('CoutKilometre', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Coût au kilomètre (€)')),
                ('FraisFixes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Frais fixes (€)')),
                ('DateDebut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('DateFin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('Distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance (km)')),
                ('CoutTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total (€)')),
                ('CommissionChauffeur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Commission chauffeur (%)')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='api.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-DateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('IdMaintenance', models.AutoField(primary_key=True, serialize=False)),
                ('DateMaintenance', models.DateTimeField(verbose_name='Date de maintenance')),
                ('TypeMaintenance', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('REVISION', 'Révision périodique'), ('REPARATION', 'Réparation'), ('AUTRE', 'Autre')], default='REVISION', max_length=20, verbose_name='Type de maintenance')),
                ('Description', models.TextField(blank=True, verbose_name='Description des travaux')),
                ('CoutMaintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût de la maintenance')),
                ('KilometrageVehicule', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage du véhicule')),
                ('DureeMaintenance', models.IntegerField(blank=True, null=True, verbose_name='Durée de la maintenance (heures)')),
                ('StatutMaintenance', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut de la maintenance')),
                ('DateFinMaintenance', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de maintenance')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdCollaborateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Technicien responsable')),
                ('IdVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('IdLivraison', models.AutoField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('PREPARATION', 'En préparation'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('RETOURNEE', 'Retournée'), ('ANNULEE', 'Annulée')], default='ATTENTE', max_length=20, verbose_name='Statut de la livraison')),
                ('DatePrevue', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue de livraison')),
                ('DateLivraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.commande', verbose_name='Commande')),
                ('IdEntrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.entrepot', verbose_name='Entrepôt source')),
                ('IdTransport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.transport', verbose_name='Transport')),
                ('IdVehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='api.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-DateCreation'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='entrepot',
            unique_together={('IdEntrepot', 'IdProduit')},
        ),
    ]
