# Generated by Django 5.1.7 on 2025-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('IdClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Fonction', models.CharField(blank=True, max_length=100)),
                ('CodePostal', models.CharField(max_length=10)),
                ('Ville', models.CharField(max_length=100)),
                ('Adresse', models.TextField()),
                ('Telephone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('RaisonSociale', models.CharField(blank=True, max_length=200)),
                ('SIRET', models.CharField(blank=True, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
