# Generated by Django 5.1.7 on 2025-03-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('IdFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('NomContact', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('PrenomContact', models.CharField(max_length=100, verbose_name='Prénom du contact')),
                ('Fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('CodePostal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('Ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('Adresse', models.TextField(verbose_name='Adresse')),
                ('Telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('RaisonSociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('SIRET', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('IdEntrepot', models.AutoField(primary_key=True, serialize=False)),
                ('Localisation', models.CharField(max_length=255, verbose_name="Localisation de l'entrepôt")),
                ('CapaciteStock', models.PositiveIntegerField(default=0, verbose_name='Capacité de stockage')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='api.product', verbose_name='Produit associé')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='StockMouvement',
            fields=[
                ('IdMouvement', models.AutoField(primary_key=True, serialize=False)),
                ('DateMouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('Quantite', models.IntegerField(verbose_name='Quantité')),
                ('TypeMouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR', 'Retour'), ('AJUSTEMENT', 'Ajustement'), ('INVENTAIRE', 'Inventaire')], default='ENTREE', max_length=20, verbose_name='Type de mouvement')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('IdCommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.commande', verbose_name='Commande associée')),
                ('IdEntrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.entrepot', verbose_name='Entrepôt')),
                ('IdFournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.fournisseur', verbose_name='Fournisseur')),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-DateMouvement'],
            },
        ),
        migrations.AddField(
            model_name='entrepot',
            name='IdMouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_associes', to='api.stockmouvement', verbose_name='Dernier mouvement associé'),
        ),
        migrations.AlterUniqueTogether(
            name='entrepot',
            unique_together={('IdEntrepot', 'IdProduit')},
        ),
    ]
