# Generated by Django 5.2.2 on 2025-06-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='LastDateMaintenance',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='IdMaintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maintenance', verbose_name='Dernière maintenance'),
        ),
    ]
