# Generated by Django 5.1.7 on 2025-03-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('IdDevis', models.AutoField(primary_key=True, serialize=False)),
                ('MontantTotalHT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total HT')),
                ('MontantTotalTTC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total TTC')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
