# Generated by Django 5.1.7 on 2025-03-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fournisseur_entrepot_stockmouvement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('IdVehicule', models.AutoField(primary_key=True, serialize=False)),
                ('TypeVehicule', models.CharField(choices=[('CAMION', 'Camion'), ('UTILITAIRE', 'Utilitaire'), ('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('AUTRE', 'Autre')], default='CAMION', max_length=20, verbose_name='Type de véhicule')),
                ('Statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_UTILISATION', 'En utilisation'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20, verbose_name='Statut du véhicule')),
                ('LastDateMaintenance', models.DateField(blank=True, null=True, verbose_name='Dernière date de maintenance')),
                ('Immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('IdTransport', models.AutoField(primary_key=True, serialize=False)),
                ('CoutKilometre', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Coût au kilomètre (€)')),
                ('FraisFixes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Frais fixes (€)')),
                ('DateDebut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('DateFin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('Distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance (km)')),
                ('CoutTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total (€)')),
                ('CommissionChauffeur', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Commission chauffeur (%)')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='api.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-DateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('IdLivreur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('CodePostal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('Ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('DateEmbauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('Statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('MALADE', 'Arrêt maladie')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdVehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreurs', to='api.vehicule', verbose_name='Véhicule attribué')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['Nom', 'Prenom'],
            },
        ),
    ]
