# Generated by Django 5.2.4 on 2025-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_quantitestock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livreur',
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Collaborateur'), (4, 'Livreur'), (5, 'ChargéStock')], verbose_name='Rôle'),
        ),
    ]
