# Generated by Django 5.1.7 on 2025-03-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vehicule_transport_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCommande', models.IntegerField()),
                ('IdProduit', models.IntegerField()),
                ('Quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('IdLivraison', models.AutoField(primary_key=True, serialize=False)),
                ('Statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('PREPARATION', 'En préparation'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('RETOURNEE', 'Retournée'), ('ANNULEE', 'Annulée')], default='ATTENTE', max_length=20, verbose_name='Statut de la livraison')),
                ('DatePrevue', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue de livraison')),
                ('DateLivraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.commande', verbose_name='Commande')),
                ('IdEntrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.entrepot', verbose_name='Entrepôt source')),
                ('IdTransport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='api.transport', verbose_name='Transport')),
                ('IdVehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='api.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-DateCreation'],
            },
        ),
    ]
