# Generated by Django 5.2.4 on 2025-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_livreur_alter_personne_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='personne',
            name='id_vehicule',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Véhicule'),
        ),
        migrations.AddField(
            model_name='personne',
            name='statut',
            field=models.CharField(blank=True, max_length=50, verbose_name='Statut'),
        ),
    ]
