# Generated by Django 5.1.7 on 2025-03-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('idCommercial', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
            },
        ),
        migrations.AddField(
            model_name='devis',
            name='idCommercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to='api.commercial', verbose_name='Commercial'),
        ),
    ]
