# Generated by Django 5.2.4 on 2025-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='produits',
            field=models.ManyToManyField(related_name='devis', to='api.product', verbose_name='Produits du devis'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Collaborateur'), (4, 'Fournisseur'), (5, 'ChargéStock')], verbose_name='Rôle'),
        ),
    ]
