# Generated by Django 5.2.4 on 2025-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_devis_produits_alter_personne_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='Approuver',
            field=models.BooleanField(default=False),
        ),
    ]
