# Generated by Django 5.1.7 on 2025-03-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detailscommande_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('IdCollaborateur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Role', models.CharField(choices=[('TECHNICIEN', 'Technicien'), ('MECANICIEN', 'Mécanicien'), ('ELECTRICIEN', 'Électricien'), ('CARROSSIER', 'Carrossier'), ('ADMINISTRATIF', 'Administratif'), ('AUTRE', 'Autre')], default='TECHNICIEN', max_length=20, verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'ordering': ['Nom', 'Prenom'],
            },
        ),
        migrations.AlterModelOptions(
            name='detailscommande',
            options={'verbose_name': 'Détail de commande', 'verbose_name_plural': 'Détails de commandes'},
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='IdCommande',
            field=models.IntegerField(verbose_name='ID de la commande'),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='IdProduit',
            field=models.IntegerField(verbose_name='ID du produit'),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='Quantite',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='detailscommande',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='detailscommande',
            unique_together={('IdCommande', 'IdProduit')},
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('IdMaintenance', models.AutoField(primary_key=True, serialize=False)),
                ('DateMaintenance', models.DateTimeField(verbose_name='Date de maintenance')),
                ('TypeMaintenance', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('REVISION', 'Révision périodique'), ('REPARATION', 'Réparation'), ('AUTRE', 'Autre')], default='REVISION', max_length=20, verbose_name='Type de maintenance')),
                ('Description', models.TextField(blank=True, verbose_name='Description des travaux')),
                ('CoutMaintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût de la maintenance')),
                ('KilometrageVehicule', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage du véhicule')),
                ('DureeMaintenance', models.IntegerField(blank=True, null=True, verbose_name='Durée de la maintenance (heures)')),
                ('StatutMaintenance', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut de la maintenance')),
                ('DateFinMaintenance', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de maintenance')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
                ('IdCollaborateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='api.collaborateur', verbose_name='Technicien responsable')),
                ('IdVehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.vehicule', verbose_name='Véhicule')),
            ],
        ),
    ]
