# Generated by Django 5.2.4 on 2025-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personne_date_embauche_personne_id_vehicule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='LastDateMaintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dernière maintenance'),
        ),
    ]
