# Generated by Django 5.1.7 on 2025-03-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commercial_devis_idcommercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ristourne',
            fields=[
                ('idRistourne', models.AutoField(primary_key=True, serialize=False)),
                ('DateRistourne', models.DateField(verbose_name='Date de la ristourne')),
                ('Montant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la ristourne')),
                ('Commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ristournes', to='api.client', verbose_name='Client')),
                ('IdCommercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ristournes_accordees', to='api.commercial', verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Ristourne',
                'verbose_name_plural': 'Ristournes',
                'ordering': ['-DateRistourne'],
            },
        ),
    ]
