# Generated by Django 5.2.4 on 2025-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vehicule_lastdatemaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Collaborateur'), (4, 'Livreur'), (5, 'ChargéStock'), (6, 'Fournisseur')], verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='TypeProduit',
            field=models.CharField(choices=[('Farines', 'Farines'), ('Produits laitiers', 'Produits laitiers'), ('Ingrédient', 'Ingrédient'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de produit'),
        ),
    ]
