# Generated by Django 5.1.7 on 2025-03-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_collaborateur_alter_detailscommande_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ristourne',
            old_name='Montant',
            new_name='MontantRistourne',
        ),
        migrations.RemoveField(
            model_name='ristourne',
            name='IdClient',
        ),
        migrations.AddField(
            model_name='ristourne',
            name='IdDevis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ristournes', to='api.devis', verbose_name='Devis'),
            preserve_default=False,
        ),
    ]
