# Generated by Django 5.2.4 on 2025-08-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_personne_role_alter_product_typeproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='NbUtilisation',
            field=models.IntegerField(default=0, verbose_name="Nombre d'utilisations"),
        ),
    ]
