# Generated by Django 5.1.7 on 2025-04-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_montant_ristourne_montantristourne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('role', models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Livreur'), (4, 'Collaborateur'), (5, 'Fournisseur')], verbose_name='Rôle')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison Sociale')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_miseajour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='IdClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.personne', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='IdClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='api.personne', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='idCommercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to='api.personne', verbose_name='Commercial'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='IdCollaborateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='api.personne', verbose_name='Technicien responsable'),
        ),
        migrations.AlterField(
            model_name='ristourne',
            name='IdCommercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ristournes_accordees', to='api.personne', verbose_name='Commercial'),
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
    ]
