# Generated by Django 5.1.7 on 2025-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_personne_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('IdLivreur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('CodePostal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('Ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('DateEmbauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('Statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('MALADE', 'Arrêt maladie')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('DateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
    ]
