# Generated by Django 5.1.7 on 2025-04-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmouvement',
            name='IdFournisseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_fournisseur', to='api.personne', verbose_name='Fournisseur'),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
