# Generated by Django 5.1.7 on 2025-04-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stockmouvement_idfournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='DatePaiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='EstPayee',
            field=models.BooleanField(default=False, verbose_name='Est payée'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.IntegerField(choices=[(1, 'Client'), (2, 'Commercial'), (3, 'Collaborateur'), (4, 'Fournisseur')], verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='stockmouvement',
            name='IdFournisseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_fournisseur', to='api.personne', verbose_name='Fournisseur'),
        ),
    ]
