# Generated by Django 5.2 on 2025-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_commande_datepaiement_commande_estpayee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
