version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DOCKER_CONTAINER=1  # This will set the environment variable
    depends_on:
      - db
    command: >
      sh -c "./wait-for-db.sh && python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 django_project.wsgi:application"
  
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=django_api_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data: