from .product import Product
from .user import UserProfile
from .devis import Devis
from .commande import Commande
from .stock import StockMouvement
from .ristourne import Ristourne
from .entrepot import Entrepot
from .vehicule import Vehicule
from .transport import Transport
from .livraison import Livraison
from .detailCommande import DetailsCommande
from .personne import Personne
from .maintenance import Maintenance
from .livreur import Livreur  