name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: django_api_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: django_api_db
      DOCKER_CONTAINER: 1
      DJANGO_SETTINGS_MODULE: django_project.settings

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PWD/Django_api" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Django_api/requirements.txt

    - name: Wait for MySQL
      run: |
        sleep 20

    - name: Run migrations
      run: |
        python Django_api/manage.py migrate

    - name: Run tests
      run: |
        pytest Django_api/api/tests/
  
  build-image:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/monapp:latest ./Django_api

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dias2001.rodrigues@gmail.com
          password: Diesel78.

      - name: Push image to Docker Hub
        run: |
          docker push dias2001.rodrigues@gmail.com/monapp:latest

